user_input1 = input("What is your favorite animal\n>")
user_input2 = input("Why are " + user_input1 + "'s your favorite animal\n>")
user_input3 = input("What food do " + user_input1 + "'s eat\n>")
user_input4 = input("What reigons do " + user_input1 + "'s live in\n>")
user_input5 = input("What is a unique fact about " + user_input1 + "'s\n>")
user_input6 = input("What are the habits of " + user_input1 + "\n>")
user_input7 = input("What kind of defenses do " + user_input1 + "'s have against predators\n>")
user_input8 = input("If a " + user_input1 + " were to fight 1,000,000 ants who would win \n>")
user_input9 = input("does a " + user_input1 + " have any sort of symiotic relationship with other animals \n>")
user_input10 = input("If a " + user_input1 + " was on the moon would it survive \n>")
print("your favorite animal is a " + user_input1 + " it's your favorite animal because " + user_input2 + " your favorite animal likes to eat " + user_input3 + " your favorite animal lives in the " + user_input4 + " a fun fact about your favorite animal is " + user_input5 + " the habits of your favorite animal are " + user_input6 + " If my favorite animal were in trouble it would " + user_input7 + " could my favorite animal beat 1,000,000 ants " + user_input8 + " what animals does my favoite animal have a symboitic relationship with" + user_input9 + " could my favorite animal survive on the moon " + user_input10)