#(your name) was always late to class, but this time Mr.(noun1) was espessially (adjective1) and (past tense verb) to know why (your name) was late. (your name)
# says that thier (noun2) (verb2), but he doesn't beleive (your name) and demands they tell the (noun 3). (Your name) thought of a quick (noun4)
# they said that (a name) (verb3) their (noun4) (adjective2) and after (a name) (verb3) the (noun5) and (verb4) into a (location) and that thats why there late.
#  Mr.(noun1) was so (adjective3) that he just let (your name) slide
name1 = input("what is your name\n>")
noun1 = input("name a noun\n>")
adjective1 = input("name an adjective\n>")
past_verb = input("name a past tense verb\n>")
noun2 = input("name a noun\n>")
verb1 = input("name a verb\n>")
noun3 = input("name a noun\n>")
noun4 = input("name a noun\n>")
name2 = input("give a random name\n>")
verb2 = input("name a verb\n>")
noun5 = input("name a noun\n>")
adjective2 = input("name an adjcective\n>")
verb3 = input("name a verb\n>")
noun6 = input("name a noun\n>")
verb3 = input ("name a verb\n>")
place = input("give the name of a building\n>")
adjective3 = input("give an adjective\n>")
print(name1 + " was always late to class, but this time Mr." + noun1 + " was espessially " + adjective1 + " and " + past_verb + " to know why " + name1 + " was late. " + name1 + " says that thier " + noun2 + " " + verb1 + " but he doesn't beleive " + name1 + " and demands they tell the " + noun3 + " " + name1 + " thought of a quick " + noun4 + " they said that " + verb3 + " their " + noun4 + " " + (adjective2) + " and after " + name1 + " " + verb2 + " the " + noun5 + " and " + verb3 + " into a " + place + " and that thats why I was late. Mr." + noun1 + " was so " + adjective3 + " that he just let " + name1 + " slide.")